language: php
php:
  - 7.4
  - 8.0
install:
  # Composer
  - composer self-update
  - composer install -n --prefer-source
before_script:
  # Directories
  - mkdir .reports
script:
  # Tests
  - php vendor/bin/phpunit --configuration ./phpunit.xml --coverage-clover=.reports/clover.xml --coverage-xml=.reports/coverage
  # Code style
  - php vendor/bin/phpcs --report=xml --report-file=.reports/phpcs.xml
after_script:
  # Coveralls
  - php vendor/bin/coveralls -v
notifications:
  email: false